version: '3.8'

services:
  mysql-db:
    image: mysql:8.0

    container_name: feedback-360-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: feedback_360
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: